---
copilot:
  workspace: obdpahwd
  description: >
    Copilot workspace for the OBDPHAWD C# project.
    Keep descriptions short and lines under 80 characters.
  settings:
    language: "C#"
    root: "."
    include:
      - "**/*.cs"
    exclude:
      - "bin/"
      - "obj/"
